# Generated by Django 4.2.4 on 2023-08-13 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='fraisAcademique',
        ),
        migrations.AddField(
            model_name='frais',
            name='designation',
            field=models.CharField(default='', max_length=155),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='frais',
            name='etudiant',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compta.etudiant')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compta.frais')),
            ],
        ),
        migrations.AddField(
            model_name='frais',
            name='etudiant',
            field=models.ManyToManyField(through='Compta.Transaction', to='Compta.etudiant'),
        ),
    ]
