# Generated by Django 4.2.4 on 2023-08-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compta', '0003_alter_frais_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='atteintFraisInscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='atteintFraisReinscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='atteintFraisSession',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='atteintFraisTranche1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='atteintFraisTranche2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='atteintFraisTranche3',
            field=models.BooleanField(default=False),
        ),
    ]
