# Generated by Django 4.2.4 on 2023-08-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compta', '0005_annee_frais_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frais',
            name='designation',
            field=models.CharField(choices=[('INSCR', 'INSCRIPTION'), ('REINSCR', 'REINSCRIPTION'), ('S', 'SESSION'), ('T1', 'TRANCHE1'), ('T2', 'TRANCHE2'), ('T3', 'TRANCHE3')], max_length=20),
        ),
    ]
