# Generated by Django 4.2.4 on 2023-08-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compta', '0008_remove_frais_atteintfraisinscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frais',
            name='designation',
            field=models.CharField(max_length=155),
        ),
    ]
