# Generated by Django 4.2.4 on 2023-08-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compta', '0011_etudiant_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='active',
        ),
    ]
